name: Image Build Pipeline  # Name of the workflow

on:  # Define the events that trigger the workflow
  push:  # Run on push events
    branches:  # Limit to specific branches (optional)
      - main
    paths: 
      - packer-images/**
      - .github/workflows/image-pipeline.yml
  pull_request:  # Run on pull request events
    branches:
      - main
    paths: 
      - packer-images/**
      - .github/workflows/image-pipeline.yml

jobs:  # Define the jobs that make up the workflow
  
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      #- id: getfilenames
      #  run: git diff --name-only --diff-filter=ACMRT ${{ github.event. }} ${{ github.sha }} | grep .pkr.hcl$ | xargs

      #converts the changed files into "real" json and filters them so only packer files are saved in the output
      - id: matrix
        run: echo "value=${{ steps.files.outputs.added_modified }}" | sed 's/\[/\["/g' | sed 's/,/","/g' | sed 's/\]/\"]/g' | jq '.[] | select(endswith(".pkr.hcl"))'| tr '\n' ',' | sed 's/,$//'| echo "[$(cat -)]" >> $GITHUB_OUTPUT 
      
  BuildImage:  # Name of the job
    needs: setup
    runs-on: ubuntu-latest  # Specify the runner environment
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    permissions:
      id-token: write # This is required for requesting the oidc JWT
      contents: read  # This is required for oidc actions/checkout
    
    steps:  # Define the steps within the job
      - run: |
          echo "${{ matrix.value }}"

      - uses: actions/checkout@v3  # Checkout the repository code

      #login with oidc aws credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050024165:role/github_action_oidc_role #replace with arn of the created OIDC identity provider in aws
          aws-region: us-east-1
        
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Build ubuntu image
        id: run
        #run: "packer init ${{ env.PACKER_FILE }};packer validate ${{ env.PACKER_FILE }};packer build ${{ env.PACKER_FILE }}"
        run: ls
  