name: Image Build Pipeline  # Name of the workflow

on:  # Define the events that trigger the workflow
  push:  # Run on push events
    branches:  # Limit to specific branches (optional)
      - main
    paths: 
      - "**.pkr.hcl"
  pull_request:  # Run on pull request events
    branches:
      - main
    paths: 
      - "**.pkr.hcl"

jobs:  # Define the jobs that make up the workflow
  
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      #- id: getfilenames
      #  run: git diff --name-only --diff-filter=ACMRT ${{ github.event. }} ${{ github.sha }} | grep .pkr.hcl$ | xargs

      #converts the changed files into "real" json and filters them so only packer files are saved in the output 
      - id: matrix
        run: echo "${{ steps.files.outputs.added_modified }}" | sed 's/\[/\["/g' | sed 's/,/","/g' | sed 's/\]/\"]/g' | jq '.[] | select(endswith(".pkr.hcl"))'| tr '\n' ',' | sed 's/,$//'| echo "value=[$(cat -)]"  >> $GITHUB_OUTPUT 
      

  BuildImage:  # Name of the job
    needs: setup
    runs-on: ubuntu-latest  # Specify the runner environment
    strategy:
      matrix: 
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    permissions:
      id-token: write # This is required for requesting the oidc JWT
      contents: read  # This is required for oidc actions/checkout
    
    steps:  # Define the steps within the job
      - run: |
          echo "${{ matrix.value }}"

      - uses: actions/checkout@v3  # Checkout the repository code

      #login with oidc aws credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050024165:role/github_action_oidc_role #replace with arn of the created OIDC identity provider in aws
          aws-region: us-east-1
        
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - id: dirname
        run: echo "dir=dirname GITHUB_WORKSPACE/${{ matrix.value }}" >> $GITHUB_OUTPUT 
      - id: filename
        run: echo "file=basename ${{ matrix.value }}" >> $GITHUB_OUTPUT 

      
      - run: cd | ${{ steps.dirname.outputs.dir }}; ls; pwd

      - name: Build image
        id: run
        run: "ls;pwd; packer init ${{ steps.filename.outputs.file }}; packer validate ${{ steps.filename.outputs.file }}; packer build ${{ steps.filename.outputs.file }}"