name: Infrastructure Pipeline  # Name of the workflow

on:  # Define the events that trigger the workflow
  push:  # Run on push events
    branches:  # Limit to specific branches (optional)
      - main
  pull_request:  # Run on pull request events
    branches:
      - main

jobs:  # Define the jobs that make up the workflow
  
  ApplyTerraform:  # Name of the job
    runs-on: ubuntu-latest  # Specify the runner environment
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      
    permissions:
      id-token: write # This is required for requesting the oidc JWT
      contents: read  # This is required for oidc actions/checkout
      
    steps:  # Define the steps within the job
      - uses: actions/checkout@v3  # Checkout the repository code

      #login with oidc aws credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050024165:role/github_action_oidc_role #replace with arn of the created OIDC identity provider in aws
          aws-region: us-east-1

      - run: cd vpc; terraform init; terraform apply -auto-approve; cd ..;pwd

        