name: Main Merge  # Name of the workflow

on:  # Define the events that trigger the workflow
  push:  # Run on push events
    branches:  # Limit to specific branches (optional)
      - main
  pull_request:  # Run on pull request events
    branches:
      - main

jobs:  # Define the jobs that make up the workflow
  
  checkcredentials:  # Name of the job
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:  # Define the steps within the job
      - uses: actions/checkout@v3  # Checkout the repository code
      - run: echo "Hello, world!";ls;ls cloudfun  # testing the command